apiVersion: 1

datasources:
  - uid: influxdb_galpao
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: true
    basicAuthUser: <admin>
    basicAuthPassword: <password>
    isDefault: true
    editable: true
    jsonData:
      httpMode: POST
      organization: <org_example>
      defaultBucket: <bucket_example>
      version: Flux
    secureJsonData:
      token: <token>
